[package]
versioned_files = ["Cargo.toml"]
changelog = "CHANGELOG.md"

[[workflows]]
name = "release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows.steps]]
type = "Command"
command = "cargo update -w && git add Cargo.lock && git commit -m \"chore: prepare release $version [skip ci]\""
variables = { "$version" = "Version" }

[[workflows.steps]]
type = "Command"
command = "git push"

[[workflows.steps]]
type = "Release"

[github]
owner = "rigetti"
repo = "quil-rs"
