[packages.quil-rs]
versioned_files = ["quil-rs/Cargo.toml"]
changelog = "quil-rs/CHANGELOG.md"
scopes = ["rs", "rust", "quil-rs"]

[packages.quil-py]
versioned_files = ["quil-py/Cargo.toml", "quil-py/pyproject.toml"]
changelog = "quil-py/CHANGELOG.md"
scopes = ["py", "python", "quil-py"]

[[workflows]]
name = "prerelease"

[[workflows.steps]]
type = "PrepareRelease"
prerelease_label = "rc"

[[workflows.steps]]
type = "Command"
command = "cargo update -w && git add Cargo.lock && git commit -m \"chore: prepare pre-release [skip ci]\""

[[workflows.steps]]
type = "Command"
command = "git push"

[[workflows.steps]]
type = "Release"

[[workflows]]
name = "release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows.steps]]
type = "Command"
command = "git add Cargo.lock && git commit -m \"chore: prepare release [skip ci]\""

[[workflows.steps]]
type = "Command"
command = "git push"

[github]
owner = "rigetti"
repo = "quil-rs"
