[packages.quil-rs]
versioned_files = ["quil-rs/Cargo.toml"]
changelog = "quil-rs/CHANGELOG.md"
scopes = ["rs", "rust", "quil-rs"]

[packages.quil-py]
versioned_files = ["quil-py/Cargo.toml", "quil-py/pyproject.toml"]
changelog = "quil-py/CHANGELOG.md"
scopes = ["py", "python", "quil-py"]

[packages.quil-cli]
versioned_files = ["quil-cli/Cargo.toml"]
changelog = "quil-cli/CHANGELOG.md"
scopes = ["cli", "quil-cli"]

[[workflows]]
name = "release"

[[workflows.steps]]
type = "PrepareRelease"

[[workflows.steps]]
type = "Command"
command = "sh ./scripts/sync_versions.sh"

[[workflows.steps]]
type = "Command"
command = "git add quil-py/Cargo.toml"

[[workflows.steps]]
type = "Command"
command = "git add quil-cli/Cargo.toml"

[[workflows.steps]]
type = "Command"
command = "git commit -m \"chore: prepare release [skip ci]\""

[[workflows.steps]]
type = "Command"
command = "git push"

[[workflows.steps]]
type = "Release"

[github]
owner = "rigetti"
repo = "quil-rs"
