[package]
name = "quil-rs"
description = "Rust tooling for Quil (Quantum Instruction Language)"
version = "0.37.1"
edition = "2021"
rust-version = "1.93"
license = "Apache-2.0"
repository = "https://github.com/rigetti/quil-rs"
keywords = ["Quil", "Quantum", "Rigetti"]
categories = ["parser-implementations", "science", "compilers", "emulators"]

[lib]
name = "quil_rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
approx = { workspace = true, features = ["num-complex"] }
dot-writer = { workspace = true, optional = true }
internment = { workspace = true, features = ["arc"] }
itertools = { workspace = true }
lexical = { workspace = true, features = ["format", "power-of-two"] }
ndarray = { workspace = true, features = ["approx"] }
nom = { workspace = true }
nom_locate = { workspace = true }
num-complex = { workspace = true }
once_cell = { workspace = true }
optipy = { workspace = true }
petgraph = { workspace = true }
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
strum = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
indexmap = { workspace = true }
statrs = { workspace = true }
paste = { workspace = true }
derive_more = { workspace = true, features = ["add", "add_assign", "display", "from", "into", "not"] }
derive-where = { workspace = true, features = ["serde"] }

# Enabled with the "python" feature.
pyo3 = { workspace = true, features = ["indexmap", "num-complex", "multiple-pymethods"], optional = true }
rigetti-pyo3 = { workspace = true, optional = true }
numpy = { workspace = true, optional = true }

# Enabled with the "stubs" feature.
pyo3-stub-gen = { workspace = true, features = ["numpy"], optional = true }
anyhow = { workspace = true, optional = true }

[dev-dependencies]
clap = { workspace = true, features = ["derive", "string"] }
criterion = { workspace = true, features = ["html_reports"] }
insta = { workspace = true }
petgraph = { workspace = true }
pretty_assertions = { workspace = true }
proptest = { workspace = true }
proptest-derive = { workspace = true }
rand = { workspace = true }
rasciigraph = { workspace = true }
rstest = { workspace = true }

[build-dependencies]
# Enabled with the "python" feature.
pyo3-build-config = { workspace = true, optional = true }

# These are described in the crate README.md
[features]
graphviz-dot = ["dep:dot-writer"]
wasm-bindgen = []
python = [ "dep:numpy", "dep:pyo3", "dep:pyo3-build-config", "dep:rigetti-pyo3" ]
stubs = [ "python", "dep:pyo3-stub-gen", "dep:anyhow", "rigetti-pyo3/stubs" ]

[[bench]]
name = "parser"
harness = false

[[bench]]
name = "get_frames_for_instruction"
harness = false

[[bench]]
name = "scheduled_program_from_program"
harness = false

[[bench]]
name = "simplification"
harness = false

[[example]]
name = "generate_test_expressions"

