# [env]
# PYTHONPATH = { script = [ "python -c 'import sysconfig; print(sysconfig.get_path(\"platlib\"))'" ] }
# RUST_BACKTRACE = 0

[tasks.install-python-deps]
description = "Install dependencies using poetry"
command = "poetry"
args = ["install", "--extras", "dev", "--no-root"]

[tasks.generate-python-stubs]
dependencies = ["install-python-deps"]
description = "Generate Python stub files."
command = "cargo"
args = ["generate-stubs"]

[tasks.install-python-package]
dependencies = ["install-python-deps"]
description = "Build the python package and install to the active virtual environment."
command = "maturin"
args = ["develop", "--features", "python"]

[tasks.install-package-with-stubs]
dependencies = ["generate-python-stubs", "install-python-pacakge"]
description = "Install the python package with up-to-date stubs (not needed for testing)."

[tasks.test]
dependencies = ["install-python-package"]
command = "pytest"
args = ["tests_py"]

[tasks.stubtest]
dependencies = ["install-package-with-stubs"]
cwd = "./python"
command = "stubtest"
args = ["quil"]

[tasks.test-all]
dependencies = ["test", "stubtest"]

[tasks.default]
alias = "test-all"

[tasks.docs]
dependencies = ["install-package-with-stubs"]
command = "pdoc"
args = ["-o", "build/docs", "quil", "--logo", "https://qcs.rigetti.com/static/img/rigetti-logo.svg"]
