# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import numpy
import numpy.typing
from quil import _quil
from quil._quil import expression
import typing
import typing_extensions
__all__ = [
    "Arithmetic",
    "ArithmeticOperand",
    "ArithmeticOperator",
    "AttributeValue",
    "BinaryLogic",
    "BinaryOperand",
    "BinaryOperator",
    "CalibrationDefinition",
    "CalibrationIdentifier",
    "Call",
    "CallArgument",
    "CallError",
    "Capture",
    "CircuitDefinition",
    "Comparison",
    "ComparisonOperand",
    "ComparisonOperator",
    "Convert",
    "Declaration",
    "DeclarationAt",
    "DefGateSequence",
    "DefGateSequenceError",
    "Delay",
    "Exchange",
    "ExternError",
    "ExternParameter",
    "ExternParameterType",
    "ExternSignature",
    "Fence",
    "FrameDefinition",
    "FrameIdentifier",
    "Gate",
    "GateDefinition",
    "GateError",
    "GateModifier",
    "GateSignature",
    "GateSpecification",
    "GateType",
    "Halt",
    "HaltType",
    "Include",
    "Instruction",
    "InstructionError",
    "Jump",
    "JumpUnless",
    "JumpWhen",
    "Label",
    "Load",
    "MeasureCalibrationDefinition",
    "MeasureCalibrationIdentifier",
    "Measurement",
    "MemoryReference",
    "Move",
    "Nop",
    "NopType",
    "Offset",
    "ParseInstructionError",
    "ParseMemoryReferenceError",
    "PauliGate",
    "PauliSum",
    "PauliTerm",
    "Pragma",
    "PragmaArgument",
    "Pulse",
    "Qubit",
    "QubitPlaceholder",
    "RawCapture",
    "Reset",
    "ScalarType",
    "SetFrequency",
    "SetPhase",
    "SetScale",
    "Sharing",
    "ShiftFrequency",
    "ShiftPhase",
    "Store",
    "SwapPhases",
    "Target",
    "TargetPlaceholder",
    "UnaryLogic",
    "UnaryOperator",
    "Vector",
    "Wait",
    "WaitType",
    "Waveform",
    "WaveformDefinition",
    "WaveformInvocation",
    "unpack_classical_reg",
]

Halt: HaltType
Nop: NopType
Wait: WaitType
class Arithmetic(Instruction):
    @property
    def destination(self) -> MemoryReference: ...
    @property
    def operator(self) -> ArithmeticOperator: ...
    @property
    def source(self) -> ArithmeticOperand: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[ArithmeticOperator, MemoryReference, ArithmeticOperand]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, operator: ArithmeticOperator, destination: MemoryReference, source: ArithmeticOperand) -> Arithmetic: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class ArithmeticOperand:
    def __getnewargs__(self) -> builtins.tuple[builtins.int | builtins.float | MemoryReference]: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...
    @typing.final
    class LiteralInteger(ArithmeticOperand):
        __match_args__ = ("_0",)
        @property
        def _0(self) -> builtins.int: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...
        def __len__(self) -> builtins.int: ...
        def __new__(cls, _0: builtins.int) -> ArithmeticOperand.LiteralInteger: ...
    
    @typing.final
    class LiteralReal(ArithmeticOperand):
        __match_args__ = ("_0",)
        @property
        def _0(self) -> builtins.float: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...
        def __len__(self) -> builtins.int: ...
        def __new__(cls, _0: builtins.float) -> ArithmeticOperand.LiteralReal: ...
    
    @typing.final
    class MemoryReference(ArithmeticOperand):
        __match_args__ = ("_0",)
        @property
        def _0(self) -> MemoryReference: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...
        def __len__(self) -> builtins.int: ...
        def __new__(cls, _0: MemoryReference) -> ArithmeticOperand.MemoryReference: ...
    

class AttributeValue:
    def __getnewargs__(self) -> builtins.tuple[builtins.str | Expression]: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...
    @typing.final
    class Expression(AttributeValue):
        __match_args__ = ("_0",)
        @property
        def _0(self) -> expression.Expression: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...
        def __len__(self) -> builtins.int: ...
        def __new__(cls, _0: expression.Expression) -> AttributeValue.Expression: ...
    
    @typing.final
    class String(AttributeValue):
        __match_args__ = ("_0",)
        @property
        def _0(self) -> builtins.str: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...
        def __len__(self) -> builtins.int: ...
        def __new__(cls, _0: builtins.str) -> AttributeValue.String: ...
    

class BinaryLogic(Instruction):
    @property
    def destination(self) -> MemoryReference: ...
    @property
    def operator(self) -> BinaryOperator: ...
    @property
    def source(self) -> BinaryOperand: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[BinaryOperator, MemoryReference, BinaryOperand]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, operator: BinaryOperator, destination: MemoryReference, source: BinaryOperand) -> BinaryLogic: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class BinaryOperand:
    def __getnewargs__(self) -> builtins.tuple[builtins.int | MemoryReference]: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...
    @typing.final
    class LiteralInteger(BinaryOperand):
        __match_args__ = ("_0",)
        @property
        def _0(self) -> builtins.int: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...
        def __len__(self) -> builtins.int: ...
        def __new__(cls, _0: builtins.int) -> BinaryOperand.LiteralInteger: ...
    
    @typing.final
    class MemoryReference(BinaryOperand):
        __match_args__ = ("_0",)
        @property
        def _0(self) -> MemoryReference: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...
        def __len__(self) -> builtins.int: ...
        def __new__(cls, _0: MemoryReference) -> BinaryOperand.MemoryReference: ...
    

class CalibrationDefinition(Instruction):
    @property
    def identifier(self) -> CalibrationIdentifier: ...
    @identifier.setter
    def identifier(self, value: CalibrationIdentifier) -> None: ...
    @property
    def instructions(self) -> builtins.list[Instruction]: ...
    @instructions.setter
    def instructions(self, value: typing.Sequence[Instruction]) -> None: ...
    @property
    def modifiers(self) -> builtins.list[GateModifier]:
        r"""
        The list of [`GateModifier`]s that this calibration definition is for.
        """
    @property
    def name(self) -> builtins.str:
        r"""
        The gate name that this calibration definition is for.
        """
    @property
    def parameters(self) -> builtins.list[expression.Expression]:
        r"""
        The list of parameters that this calibration definition is for.
        """
    @property
    def qubits(self) -> builtins.list[Qubit]:
        r"""
        The list of [`Qubit`]s that this calibration definition is for.
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[CalibrationIdentifier, builtins.list[Instruction]]: ...
    def __new__(cls, identifier: CalibrationIdentifier, instructions: typing.Sequence[Instruction]) -> CalibrationDefinition:
        r"""
        Builds a new calibration definition.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class CalibrationIdentifier:
    r"""
    Unique identifier for a calibration definition within a program
    """
    @property
    def modifiers(self) -> builtins.list[GateModifier]:
        r"""
        The modifiers applied to the gate
        """
    @modifiers.setter
    def modifiers(self, value: typing.Sequence[GateModifier]) -> None:
        r"""
        The modifiers applied to the gate
        """
    @property
    def name(self) -> builtins.str:
        r"""
        The name of the gate
        """
    @name.setter
    def name(self, value: builtins.str) -> None:
        r"""
        The name of the gate
        """
    @property
    def parameters(self) -> builtins.list[expression.Expression]:
        r"""
        The parameters of the gate - these are the variables in the calibration definition
        """
    @parameters.setter
    def parameters(self, value: typing.Sequence[expression.Expression]) -> None:
        r"""
        The parameters of the gate - these are the variables in the calibration definition
        """
    @property
    def qubits(self) -> builtins.list[Qubit]:
        r"""
        The qubits on which the gate is applied
        """
    @qubits.setter
    def qubits(self, value: typing.Sequence[Qubit]) -> None:
        r"""
        The qubits on which the gate is applied
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[builtins.str, builtins.list[expression.Expression], builtins.list[Qubit], builtins.list[GateModifier]]: ...
    def __new__(cls, name: builtins.str, parameters: typing.Sequence[expression.Expression], qubits: typing.Sequence[Qubit], modifiers: typing.Sequence[GateModifier]) -> CalibrationIdentifier:
        r"""
        Builds a new calibration identifier.
        
        Raises an error if the given name isn't a valid Quil identifier.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class Call(Instruction):
    r"""
    A call instruction with a name and arguments.
    
    An instruction that calls an external function declared with a `PRAGMA EXTERN` instruction.
    These calls are generally specific to a particular hardware or virtual machine backend.
    
    For further detail, see:
    
    * [Other instructions and Directives](https://github.com/quil-lang/quil/blob/master/rfcs/extern-call.md) in the Quil specification.
    * [EXTERN / CALL RFC](https://github.com/quil-lang/quil/blob/master/rfcs/extern-call.md)
    * [quil#87](https://github.com/quil-lang/quil/issues/87)
    
    Also see [`ExternSignature`].
    """
    @property
    def arguments(self) -> builtins.list[CallArgument]:
        r"""
        The arguments of the call instruction.
        """
    @property
    def name(self) -> builtins.str:
        r"""
        The name of the call instruction. This must be a valid user identifier.
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[builtins.str, builtins.list[CallArgument]]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, name: builtins.str, arguments: typing.Sequence[CallArgument]) -> Call:
        r"""
        Create a new call instruction with resolved arguments.
        This will validate the name as a user identifier.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class CallArgument:
    r"""
    A parsed, but unresolved call argument. This may be resolved into a [`ResolvedCallArgument`]
    with the appropriate [`ExternSignature`]. Resolution is required for building the
    [`crate::Program`] memory graph.
    """
    def __getnewargs__(self) -> builtins.tuple[builtins.str | MemoryReference | builtins.complex]: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...
    @typing.final
    class Identifier(CallArgument):
        r"""
        A reference to a declared memory location. Note, this may be resolved to either
        a scalar or vector. In the former case, the assumed index is 0.
        """
        __match_args__ = ("_0",)
        @property
        def _0(self) -> builtins.str: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...
        def __len__(self) -> builtins.int: ...
        def __new__(cls, _0: builtins.str) -> CallArgument.Identifier: ...
    
    @typing.final
    class Immediate(CallArgument):
        r"""
        An immediate value. This may be resolved to a non-mutable scalar.
        """
        __match_args__ = ("_0",)
        @property
        def _0(self) -> builtins.complex: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...
        def __len__(self) -> builtins.int: ...
        def __new__(cls, _0: builtins.complex) -> CallArgument.Immediate: ...
    
    @typing.final
    class MemoryReference(CallArgument):
        r"""
        A reference to a memory location. This may be resolved to a scalar.
        """
        __match_args__ = ("_0",)
        @property
        def _0(self) -> MemoryReference: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...
        def __len__(self) -> builtins.int: ...
        def __new__(cls, _0: MemoryReference) -> CallArgument.MemoryReference: ...
    

class CallError(_quil.QuilError):
    r"""
    Errors that may occur when initializing a ``Call``.
    """
    ...

class Capture(Instruction):
    @property
    def blocking(self) -> builtins.bool: ...
    @blocking.setter
    def blocking(self, value: builtins.bool) -> None: ...
    @property
    def frame(self) -> FrameIdentifier: ...
    @frame.setter
    def frame(self, value: FrameIdentifier) -> None: ...
    @property
    def memory_reference(self) -> MemoryReference: ...
    @memory_reference.setter
    def memory_reference(self, value: MemoryReference) -> None: ...
    @property
    def waveform(self) -> WaveformInvocation: ...
    @waveform.setter
    def waveform(self, value: WaveformInvocation) -> None: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[builtins.bool, FrameIdentifier, MemoryReference, WaveformInvocation]: ...
    def __new__(cls, blocking: builtins.bool, frame: FrameIdentifier, memory_reference: MemoryReference, waveform: WaveformInvocation) -> Capture: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class CircuitDefinition(Instruction):
    @property
    def instructions(self) -> builtins.list[Instruction]: ...
    @instructions.setter
    def instructions(self, value: typing.Sequence[Instruction]) -> None: ...
    @property
    def name(self) -> builtins.str: ...
    @name.setter
    def name(self, value: builtins.str) -> None: ...
    @property
    def parameters(self) -> builtins.list[builtins.str]: ...
    @parameters.setter
    def parameters(self, value: typing.Sequence[builtins.str]) -> None: ...
    @property
    def qubit_variables(self) -> builtins.list[builtins.str]: ...
    @qubit_variables.setter
    def qubit_variables(self, value: typing.Sequence[builtins.str]) -> None: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[builtins.str, builtins.list[builtins.str], builtins.list[builtins.str], builtins.list[Instruction]]: ...
    def __new__(cls, name: builtins.str, parameters: typing.Sequence[builtins.str], qubit_variables: typing.Sequence[builtins.str], instructions: typing.Sequence[Instruction]) -> CircuitDefinition: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class Comparison(Instruction):
    @property
    def destination(self) -> MemoryReference: ...
    @property
    def lhs(self) -> MemoryReference: ...
    @property
    def operator(self) -> ComparisonOperator: ...
    @property
    def rhs(self) -> ComparisonOperand: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[ComparisonOperator, MemoryReference, MemoryReference, ComparisonOperand]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, operator: ComparisonOperator, destination: MemoryReference, lhs: MemoryReference, rhs: ComparisonOperand) -> Comparison: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class ComparisonOperand:
    def __getnewargs__(self) -> builtins.tuple[builtins.int | builtins.float | MemoryReference]: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...
    @typing.final
    class LiteralInteger(ComparisonOperand):
        __match_args__ = ("_0",)
        @property
        def _0(self) -> builtins.int: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...
        def __len__(self) -> builtins.int: ...
        def __new__(cls, _0: builtins.int) -> ComparisonOperand.LiteralInteger: ...
    
    @typing.final
    class LiteralReal(ComparisonOperand):
        __match_args__ = ("_0",)
        @property
        def _0(self) -> builtins.float: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...
        def __len__(self) -> builtins.int: ...
        def __new__(cls, _0: builtins.float) -> ComparisonOperand.LiteralReal: ...
    
    @typing.final
    class MemoryReference(ComparisonOperand):
        __match_args__ = ("_0",)
        @property
        def _0(self) -> MemoryReference: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...
        def __len__(self) -> builtins.int: ...
        def __new__(cls, _0: MemoryReference) -> ComparisonOperand.MemoryReference: ...
    

class Convert(Instruction):
    @property
    def destination(self) -> MemoryReference: ...
    @property
    def source(self) -> MemoryReference: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[MemoryReference, MemoryReference]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, destination: MemoryReference, source: MemoryReference) -> Convert: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class Declaration(Instruction):
    @property
    def name(self) -> builtins.str: ...
    @property
    def sharing(self) -> typing.Optional[Sharing]: ...
    @property
    def size(self) -> Vector: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getitem__(self, index: builtins.int) -> DeclarationAt:
        r"""
        Return a new `DeclarationAt` to this `Declaration` at the given `index`.
        
        The result can be used in places where a `MemoryReference` is expected,
        but has the advantage of sharing the underlying `Declaration` object;
        that allows it to use less memory and to validate certain memory operations
        while constructing a `quil.program.Program`.
        """
    def __getnewargs__(self) -> tuple[builtins.str, ScalarType, builtins.int, typing.Optional[builtins.str], typing.Optional[builtins.list[tuple[builtins.int, ScalarType]]]]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, name: builtins.str, memory_type: ScalarType  |  typing.Literal["BIT", "INTEGER", "REAL", "OCTET"], memory_size: builtins.int = 1, shared_region: typing.Optional[builtins.str] = None, offsets: typing.Optional[typing.Sequence[tuple[builtins.int, ScalarType  |  typing.Literal["BIT", "INTEGER", "REAL", "OCTET"]]]] = None) -> Declaration: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

@typing.final
class DeclarationAt:
    r"""
    A wrapper around a [`Declaration`] for use in places we'd normally need a `MemoryReference`.
    
    You can get an instance of `DeclarationAt` by indexing a `Declaration`,
    and you can then use it in places where a `MemoryReference` is expected.
    The underlying objects share the same `Declaration` memory
    and can provide additional validation on bounds-checking.
    
    # Example
    
    With use of the warlus operator, you can often write a list of instructions
    without needing to explicitly declare `MemoryReference` objects:
    
    ```python
    instructions = [
        top := Label("top"),                                        # LABEL @top
        counter := Declaration("counter", ScalarType.INTEGER),      # DECLARE counter INTEGER
        counter[0].move(10),                                        # MOVE counter[0] 10
        # additional instructions...
        counter[0] - 1,                                             # SUB counter[0] 1
        JumpWhen(top, counter[0]),                                  # JUMP-WHEN @top counter[0]
    ]
    ```
    """
    def add(self, other: ArithmeticOperand  |  builtins.int  |  builtins.float  |  MemoryReference  |  DeclarationAt  |  Declaration) -> Arithmetic:
        r"""
        Return a new `Arithmetic` instruction representing `ADD self other`.
        
        # Example
        
        ```python
        from quil.instructions import Declaration, ScalarType
        
        x = Declaration("x", ScalarType.INTEGER, 3)
        arith = x[2].add(5)
        assert isinstance(arith, Arithmetic)
        assert arith.to_quil() == "ADD x[2] 5"
        ```
        """
    def div(self, other: ArithmeticOperand  |  builtins.int  |  builtins.float  |  MemoryReference  |  DeclarationAt  |  Declaration) -> Arithmetic: ...
    def move(self, source: ArithmeticOperand) -> Move:
        r"""
        Return a new `Move` instruction representing `self = source`.
        """
    def mul(self, other: ArithmeticOperand  |  builtins.int  |  builtins.float  |  MemoryReference  |  DeclarationAt  |  Declaration) -> Arithmetic: ...
    def sub(self, other: ArithmeticOperand  |  builtins.int  |  builtins.float  |  MemoryReference  |  DeclarationAt  |  Declaration) -> Arithmetic: ...

class DefGateSequence:
    r"""
    A sequence of gates that make up a defined gate (i.e. with `DEFGATE ... AS SEQUENCE`).
    """
    @property
    def gates(self) -> builtins.list[Gate]:
        r"""
        The list of `Gate` objects that make up the sequence.
        """
    @property
    def qubits(self) -> builtins.list[builtins.str]:
        r"""
        The list of qubit variable names in the gate signature.
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[builtins.list[builtins.str], builtins.list[Gate]]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, qubits: typing.Sequence[builtins.str], gates: typing.Sequence[Gate]) -> DefGateSequence:
        r"""
        Creates a new `DefGateSequence` with the given qubits and gates.
        
        `qubits` should be a list of qubit names that the gates in the sequence will act on.
        `gates` should be a list of `Gate` objects that make up the sequence.
        Each gate must reference qubits in the `qubits` list by name.
        They may not specify a fixed qubit.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """

class DefGateSequenceError(InstructionError):
    r"""
    Errors that can occur when initializing a sequence gate definition.
    """
    ...

class Delay(Instruction):
    @property
    def duration(self) -> expression.Expression: ...
    @property
    def frame_names(self) -> builtins.list[builtins.str]: ...
    @property
    def qubits(self) -> builtins.list[Qubit]: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[expression.Expression, builtins.list[builtins.str], builtins.list[Qubit]]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, duration: expression.Expression, frame_names: typing.Sequence[builtins.str], qubits: typing.Sequence[Qubit]) -> Delay: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class Exchange(Instruction):
    @property
    def left(self) -> MemoryReference: ...
    @property
    def right(self) -> MemoryReference: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[MemoryReference, MemoryReference]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, left: MemoryReference, right: MemoryReference) -> Exchange: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class ExternError(_quil.QuilError):
    r"""
    Errors that may occur when initializing or validating a ``PRAGMA EXTERN`` instruction.
    """
    ...

class ExternParameter:
    r"""
    An extern parameter with a name, mutability, and data type.
    """
    @property
    def data_type(self) -> ExternParameterType:
        r"""
        The data type of the parameter.
        """
    @property
    def mutable(self) -> builtins.bool:
        r"""
        Whether the parameter is mutable.
        """
    @property
    def name(self) -> builtins.str:
        r"""
        The name of the parameter. This must be a valid user identifier.
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[builtins.str, builtins.bool, ExternParameterType]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, name: builtins.str, mutable: builtins.bool, data_type: ExternParameterType) -> ExternParameter:
        r"""
        Create a new extern parameter. This will fail if the parameter name
        is not a valid user identifier.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class ExternParameterType:
    r"""
    A parameter type within an extern signature.
    """
    def __getnewargs__(self) -> builtins.tuple[ScalarType | Vector]: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...
    @typing.final
    class FixedLengthVector(ExternParameterType):
        r"""
        A fixed-length vector, which must accept a memory region name of the appropriate
        length and data type.
        
        For instance `PRAGMA EXTERN foo "(bar : INTEGER[2])"`.
        """
        __match_args__ = ("_0",)
        @property
        def _0(self) -> Vector: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...
        def __len__(self) -> builtins.int: ...
        def __new__(cls, _0: Vector) -> ExternParameterType.FixedLengthVector: ...
    
    @typing.final
    class Scalar(ExternParameterType):
        r"""
        A scalar parameter, which may accept a memory reference or immediate value.
        
        For instance `PRAGMA EXTERN foo "(bar : INTEGER)"`.
        """
        __match_args__ = ("_0",)
        @property
        def _0(self) -> ScalarType: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...
        def __len__(self) -> builtins.int: ...
        def __new__(cls, _0: ScalarType) -> ExternParameterType.Scalar: ...
    
    @typing.final
    class VariableLengthVector(ExternParameterType):
        r"""
        A variable-length vector, which must accept a memory region name of the appropriate
        data type.
        
        For instance `PRAGMA EXTERN foo "(bar : INTEGER[])"`.
        """
        __match_args__ = ("_0",)
        @property
        def _0(self) -> ScalarType: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...
        def __len__(self) -> builtins.int: ...
        def __new__(cls, _0: ScalarType) -> ExternParameterType.VariableLengthVector: ...
    

class ExternSignature:
    r"""
    An extern signature with a return type and parameters.
    
    The signature of a ``PRAGMA EXTERN`` instruction.
    This signature is defined by a list of ``ExternParameter``s and an optional return type.
    See the [Quil Specification](https://github.com/quil-lang/quil/blob/7f532c7cdde9f51eae6abe7408cc868fba9f91f6/specgen/spec/sec-other.s)
    for details on how these signatures are formed.
    """
    @property
    def parameters(self) -> builtins.list[ExternParameter]:
        r"""
        The parameters of the extern signature.
        """
    @property
    def return_type(self) -> typing.Optional[ScalarType]:
        r"""
        The return type of the extern signature, if any.
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[typing.Optional[ScalarType], builtins.list[ExternParameter]]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, return_type: typing.Optional[ScalarType], parameters: typing.Sequence[ExternParameter]) -> ExternSignature:
        r"""
        Create a new extern signature.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class Fence(Instruction):
    @property
    def qubits(self) -> builtins.list[Qubit]: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[builtins.list[Qubit]]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, qubits: typing.Sequence[Qubit]) -> Fence: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class FrameDefinition(Instruction):
    @property
    def attributes(self) -> builtins.dict[builtins.str, AttributeValue]: ...
    @attributes.setter
    def attributes(self, value: typing.Mapping[builtins.str, AttributeValue]) -> None: ...
    @property
    def identifier(self) -> FrameIdentifier: ...
    @identifier.setter
    def identifier(self, value: FrameIdentifier) -> None: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[FrameIdentifier, builtins.dict[builtins.str, AttributeValue]]: ...
    def __new__(cls, identifier: FrameIdentifier, attributes: typing.Mapping[builtins.str, AttributeValue]) -> FrameDefinition: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class FrameIdentifier:
    @property
    def name(self) -> builtins.str: ...
    @property
    def qubits(self) -> builtins.list[Qubit]: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[builtins.list[Qubit], builtins.str]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, qubits: typing.Sequence[Qubit], name: builtins.str) -> FrameIdentifier: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def __str__(self) -> builtins.str:
        r"""
        Get a Quil-like representation as a string.
        """
    def out(self) -> builtins.str:
        r"""
        Get a Quil representation as a string.
        
        This method is deprecated; you should use `to_quil` instead.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class Gate(Instruction):
    r"""
    A struct encapsulating all the properties of a Quil Quantum Gate.
    """
    @property
    def modifiers(self) -> builtins.list[GateModifier]: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def parameters(self) -> builtins.list[expression.Expression]: ...
    @property
    def qubits(self) -> builtins.list[Qubit]: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple: ...
    def __hash__(self) -> builtins.int: ...
    @typing.overload
    def __new__(cls, name: builtins.str, parameters: typing.Sequence[expression.Expression  |  MemoryReference  |  builtins.int  |  builtins.float  |  builtins.complex], qubits: typing.Sequence[Qubit  |  QubitPlaceholder  |  builtins.int  |  builtins.str], modifiers: typing.Optional[typing.Sequence[GateModifier  |  builtins.str]] = None) -> Gate: ...
    @typing.overload
    def __new__(cls, name: builtins.str, *, qubits: typing.Sequence[Qubit  |  QubitPlaceholder  |  builtins.int  |  builtins.str], modifiers: typing.Optional[typing.Sequence[GateModifier  |  builtins.str]] = None, params: typing.Optional[typing.Sequence[expression.Expression  |  MemoryReference  |  builtins.int  |  builtins.float  |  builtins.complex]] = None) -> typing_extensions.NoReturn: ...
    @typing.overload
    def __new__(cls, name: builtins.str, parameters: typing.Sequence[expression.Expression  |  MemoryReference  |  builtins.int  |  builtins.float  |  builtins.complex], qubits: typing.Sequence[Qubit  |  QubitPlaceholder  |  builtins.int  |  builtins.str], modifiers: typing.Optional[typing.Sequence[GateModifier  |  builtins.str]] = None, *, params: typing.Optional[typing.Sequence[expression.Expression  |  MemoryReference  |  builtins.int  |  builtins.float  |  builtins.complex]] = None) -> Gate:
        r"""
        Create a new ``Gate``.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def __str__(self) -> builtins.str:
        r"""
        Get a Quil-like representation as a string.
        """
    def controlled(self, control_qubit: Qubit  |  QubitPlaceholder  |  builtins.int  |  builtins.str) -> Gate:
        r"""
        Return a copy of the ``Gate`` with the ``CONTROLLED`` modifier added to it.
        """
    def dagger(self) -> Gate:
        r"""
        Return a copy of the ``Gate`` with the ``DAGGER`` modifier added to it.
        """
    def forked(self, fork_qubit: Qubit  |  QubitPlaceholder  |  builtins.int  |  builtins.str, alt_params: typing.Sequence[expression.Expression]) -> Gate:
        r"""
        Return a copy of the ``Gate`` with the ``FORKED`` modifier added to it.
        
        Raises a ``GateError`` if the number of provided alternate parameters
        don't equal the number of existing parameters.
        """
    def out(self) -> builtins.str:
        r"""
        Get a Quil representation as a string.
        
        This method is deprecated; you should use `to_quil` instead.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...
    def to_unitary(self, n_qubits: builtins.int) -> numpy.typing.NDArray[numpy.complex128]:
        r"""
        Get the matrix resulting from lifting this ``Gate``
        to the full `n_qubits`-qubit Hilbert space.
        
        Raises a ``GateError`` if any of the parameters of this ``Gate`` are non-constant,
        if any of the ``Qubit``s are variable,
        if the name of this ``Gate`` is unknown,
        or if there are an unexpected number of parameters.
        
        # Notes
        
        A previous version of this library called this `to_unitary_mut`,
        and modified the ``Gate`` when called.
        This is no longer possible, as it would modify the ``Gate``'s hash,
        leading to confusing bugs.
        ``Gate``s, as well as all other hashable classes, are immutable from Python.
        
        # Bugs
        
        Supplying `n_qubits` as `0` will raise an unspecified exception;
        other invalid input parameters may silently return an invalid result.
        """

class GateDefinition(Instruction):
    r"""
    A struct encapsulating a quil Gate Definition
    """
    @property
    def name(self) -> builtins.str: ...
    @property
    def parameters(self) -> builtins.list[builtins.str]: ...
    @property
    def signature(self) -> GateSignature: ...
    @property
    def specification(self) -> GateSpecification: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[builtins.str, builtins.list[builtins.str], GateSpecification]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, name: builtins.str, parameters: typing.Sequence[builtins.str], specification: GateSpecification) -> GateDefinition: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class GateError(_quil.QuilError):
    r"""
    Errors that may occur when performing operations on a ``Gate``.
    """
    ...

class GateSignature:
    r"""
    A signature for a gate definition; this does not include the gate definition content.
    To get a signature from a definition, use `GateDefinition.signature`.
    """
    @property
    def gate_parameters(self) -> builtins.list[builtins.str]: ...
    @property
    def gate_type(self) -> GateType: ...
    @property
    def name(self) -> builtins.str: ...
    @property
    def qubit_parameters(self) -> builtins.list[builtins.str]: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[builtins.str, builtins.list[builtins.str], builtins.list[builtins.str], GateType]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, name: builtins.str, gate_parameters: typing.Sequence[builtins.str], qubit_parameters: typing.Sequence[builtins.str], gate_type: GateType) -> GateSignature: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """

class GateSpecification:
    r"""
    An enum representing a the specification of a [`GateDefinition`] for a given [`GateType`]
    """
    def __getnewargs__(self) -> builtins.tuple[builtins.list[builtins.list[expression.Expression]] | builtins.list[builtins.int] | PauliSum | DefGateSequence]: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...
    @typing.final
    class Matrix(GateSpecification):
        r"""
        A matrix of [`Expression`]s representing a unitary operation for a [`GateType::Matrix`].
        """
        __match_args__ = ("_0",)
        @property
        def _0(self) -> builtins.list[builtins.list[expression.Expression]]: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...
        def __len__(self) -> builtins.int: ...
        def __new__(cls, _0: typing.Sequence[typing.Sequence[expression.Expression]]) -> GateSpecification.Matrix: ...
    
    @typing.final
    class PauliSum(GateSpecification):
        r"""
        A Hermitian operator specified as a Pauli sum, a sum of combinations of Pauli operators,
        used for a [`GateType::PauliSum`]
        """
        __match_args__ = ("_0",)
        @property
        def _0(self) -> PauliSum: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...
        def __len__(self) -> builtins.int: ...
        def __new__(cls, _0: PauliSum) -> GateSpecification.PauliSum: ...
    
    @typing.final
    class Permutation(GateSpecification):
        r"""
        A vector of integers that defines the permutation used for a [`GateType::Permutation`]
        """
        __match_args__ = ("_0",)
        @property
        def _0(self) -> builtins.list[builtins.int]: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...
        def __len__(self) -> builtins.int: ...
        def __new__(cls, _0: typing.Sequence[builtins.int]) -> GateSpecification.Permutation: ...
    
    @typing.final
    class Sequence(GateSpecification):
        r"""
        A sequence of gates.
        """
        __match_args__ = ("_0",)
        @property
        def _0(self) -> DefGateSequence: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...
        def __len__(self) -> builtins.int: ...
        def __new__(cls, _0: DefGateSequence) -> GateSpecification.Sequence: ...
    

@typing.final
class HaltType(Instruction):
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls) -> HaltType:
        r"""
        Create a new instance of this instruction type.
        
        Users should not call this method, but it is provided for `pickle` support.
        """

class Include(Instruction):
    @property
    def filename(self) -> builtins.str: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[builtins.str]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, filename: builtins.str) -> Include: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class Instruction:
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def is_quil_t(self) -> builtins.bool:
        r"""
        Returns true if the instruction is a Quil-T instruction.
        """

class InstructionError(_quil.QuilError):
    r"""
    Base error type for errors related to ``Instruction`` processing.
    """
    ...

class Jump(Instruction):
    @property
    def target(self) -> Target: ...
    @target.setter
    def target(self, value: Target) -> None: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[Target]: ...
    def __new__(cls, target: Target) -> Jump: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class JumpUnless(Instruction):
    @property
    def condition(self) -> MemoryReference: ...
    @condition.setter
    def condition(self, value: MemoryReference) -> None: ...
    @property
    def target(self) -> Target: ...
    @target.setter
    def target(self, value: Target) -> None: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[Target, MemoryReference]: ...
    def __new__(cls, target: Target, condition: MemoryReference) -> JumpUnless: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class JumpWhen(Instruction):
    @property
    def condition(self) -> MemoryReference: ...
    @condition.setter
    def condition(self, value: MemoryReference) -> None: ...
    @property
    def target(self) -> Target: ...
    @target.setter
    def target(self, value: Target) -> None: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[Target, MemoryReference]: ...
    def __new__(cls, target: Target, condition: MemoryReference) -> JumpWhen: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class Label(Instruction):
    @property
    def name(self) -> builtins.str:
        r"""
        Get the `Label`'s name, assuming it is a `Fixed` target.
        
        This is deprecated because a `Label`'s `target` might not be `Fixed`.
        """
    @property
    def target(self) -> Target: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[Target]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, target: typing.Optional[builtins.str  |  Label  |  Target] = None, *, placeholder: typing.Optional[builtins.bool] = None) -> Label:
        r"""
        Create a new `Label`.
        
        A `Label` represents a ``LABEL`` instruction, which in Quil reads as ``LABEL @target-name``.
        Labels are used by unconditional jump instructions, e.g. ``JUMP @target-name``,
        and its siblings, ``JUMP-WHEN @target-name foo[0]`` and ``JUMP-UNLESS @target-name bar[0]``.
        The `@target-name` part of these instructions is this class's ``target`` attribute.
        
        # Example Usage
        
        You can use a `Label` directly as the ``target`` of a ``Jump`` instruction.
        
        ```python
        prog = Program(
            top := Label("top"),
            counter_memory := Declaration("counter", ScalarType.INTEGER),
            Declaration("ro", ScalarType.BIT, 2),
            H(0),
            Jump(top),
        )
        prog.resolve_placeholders()
        print(prog.to_quil())
        ```
        
        Use ``Program.resolve_placeholders()`` to fill in the value before outputting Quil::
        You can construct a `Label` with a fixed `target` using ``Label("some-name")``,
        and then you can reference that point using, for example, ``Jump("some-name")``.
        
        You can create a new `Label` from a particular `Target`,
        or you can let the constructor create the `Target` instance for you.
        Use ``Label("name")`` for fixed target or ``Label()`` to create a placeholder target;
        if you want a placeholder with a specific `base_label`,
        you'll need to specify ``Label("name", placeholder=True)``.
        
        To summarize:
        
        |   Simple                         |   Equivalent                                                   |
        | -------------------------------- | -------------------------------------------------------------- |
        | `Label("A")`                     | `Label(Target.Fixed("A"))`                                     |
        | `Label()`                        | `Label(Target.Placeholder(TargetPlaceholder(base_label="L")))` |
        | `Label("A", placeholder=True)`   | `Label(Target.Placeholder(TargetPlaceholder(base_label="A")))` |
        """
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def __str__(self) -> builtins.str:
        r"""
        Get a Quil-like representation as a string.
        """
    def out(self) -> builtins.str:
        r"""
        Get a Quil representation as a string.
        
        This method is deprecated; you should use `to_quil` instead.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class Load(Instruction):
    @property
    def destination(self) -> MemoryReference: ...
    @property
    def offset(self) -> MemoryReference: ...
    @property
    def source(self) -> builtins.str: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[MemoryReference, builtins.str, MemoryReference]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, destination: MemoryReference, source: builtins.str, offset: MemoryReference) -> Load: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class MeasureCalibrationDefinition(Instruction):
    @property
    def identifier(self) -> MeasureCalibrationIdentifier: ...
    @identifier.setter
    def identifier(self, value: MeasureCalibrationIdentifier) -> None: ...
    @property
    def instructions(self) -> builtins.list[Instruction]: ...
    @instructions.setter
    def instructions(self, value: typing.Sequence[Instruction]) -> None: ...
    @property
    def name(self) -> typing.Optional[builtins.str]:
        r"""
        The Quil-T name of the measurement that this measure calibration definition is for, if any.
        """
    @property
    def qubit(self) -> Qubit:
        r"""
        The qubit that this measure calibration definition is for.
        """
    @property
    def target(self) -> typing.Optional[builtins.str]:
        r"""
        The name the measurement calibration uses for the variable it will write the measurement
        result to, if this is a measurement for record.
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[MeasureCalibrationIdentifier, builtins.list[Instruction]]: ...
    def __new__(cls, identifier: MeasureCalibrationIdentifier, instructions: typing.Sequence[Instruction]) -> MeasureCalibrationDefinition: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class MeasureCalibrationIdentifier:
    r"""
    A unique identifier for a measurement calibration definition within a program
    """
    @property
    def name(self) -> typing.Optional[builtins.str]:
        r"""
        The Quil-T name of the measurement, if any.
        """
    @name.setter
    def name(self, value: typing.Optional[builtins.str]) -> None:
        r"""
        The Quil-T name of the measurement, if any.
        """
    @property
    def qubit(self) -> Qubit:
        r"""
        The qubit which is being measured.
        """
    @qubit.setter
    def qubit(self, value: Qubit) -> None:
        r"""
        The qubit which is being measured.
        """
    @property
    def target(self) -> typing.Optional[builtins.str]:
        r"""
        The name the definition uses for the variable it will write the measurement result to, if
        this is a measurement for record.
        
        If this is missing, this is a calibration for a measurement for effect.
        """
    @target.setter
    def target(self, value: typing.Optional[builtins.str]) -> None:
        r"""
        The name the definition uses for the variable it will write the measurement result to, if
        this is a measurement for record.
        
        If this is missing, this is a calibration for a measurement for effect.
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs_ex__(self) -> builtins.tuple[
            builtins.tuple[Qubit, typing.Optional[builtins.str]],
            builtins.dict[builtins.str, typing.Optional[builtins.str]]
        ]: ...
    def __new__(cls, qubit: Qubit, target: typing.Optional[builtins.str], *, name: typing.Optional[builtins.str] = None) -> MeasureCalibrationIdentifier: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class Measurement(Instruction):
    @property
    def name(self) -> typing.Optional[builtins.str]: ...
    @property
    def qubit(self) -> Qubit: ...
    @property
    def target(self) -> typing.Optional[MemoryReference]: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs_ex__(self) -> builtins.tuple[
            builtins.tuple[Qubit, typing.Optional[MemoryReference]],
            builtins.dict[builtins.str, typing.Optional[builtins.str]]
        ]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, qubit: Qubit, target: typing.Optional[MemoryReference], *, name: typing.Optional[builtins.str] = None) -> Measurement: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class MemoryReference:
    r"""
    Representation of a reference to a classical memory address.
    """
    @property
    def declared_size(self) -> None: ...
    @property
    def index(self) -> builtins.int:
        r"""
        The offset into the memory region.
        """
    @property
    def name(self) -> builtins.str:
        r"""
        The name of the variable.
        """
    @property
    def offset(self) -> builtins.int: ...
    def __add__(self, other: ArithmeticOperand) -> Arithmetic:
        r"""
        Return a new `Arithmetic` instruction
        representing the addition of this `MemoryReference` to the given operand.
        
        # Example
        
        ```python
        from quil.instructions import MemoryReference, Arithmetic
        
        mem_ref = MemoryReference("counter", 0)
        arith = mem_ref + 5
        assert isinstance(arith, Arithmetic)
        assert arith.to_quil() == "ADD counter[0] 5"
        ```
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getitem__(self, index: builtins.int) -> MemoryReference:
        r"""
        Return a new `MemoryReference` with the given `index`.
        
        This requires that `self` has an `index` of 0.
        """
    def __getnewargs__(self) -> tuple[str, int, int | None]: ...
    def __hash__(self) -> builtins.int: ...
    def __mul__(self, other: ArithmeticOperand) -> Arithmetic: ...
    def __new__(cls, name: builtins.str, index: builtins.int = 0, declared_size: typing.Optional[builtins.int] = None, *, offset: typing.Optional[builtins.int] = None) -> MemoryReference:
        r"""
        Construct a new `MemoryReference`.
        
        The `declared_size` parameter is deprecated and no longer used.
        Previously, it was only used to pretty-print `MemoryReference`s
        by hiding the square brackets (``[]``) when they weren't technically necessary.
        If the parameter is passed or the attribute accessed,
        it'll issue a ``DeprecationWarning``.
        
        Note that `offset` is an older (deprecated) term for `index`.
        New code should use `index`, but using `offset` as a keyword argument is still accepted;
        if it is not `None`, it'll be used instead of `index`, regardless of how `index` is passed.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def __str__(self) -> builtins.str:
        r"""
        Get a Quil-like representation as a string.
        """
    def __sub__(self, other: ArithmeticOperand) -> Arithmetic: ...
    def __truediv__(self, other: ArithmeticOperand) -> Arithmetic: ...
    @staticmethod
    def _from_parameter_str(memory_reference_str: builtins.str) -> MemoryReference: ...
    def out(self) -> builtins.str:
        r"""
        Get a Quil representation as a string.
        
        This method is deprecated; you should use `to_quil` instead.
        """
    @staticmethod
    def parse(string: builtins.str) -> MemoryReference: ...
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class Move(Instruction):
    @property
    def destination(self) -> MemoryReference: ...
    @property
    def source(self) -> ArithmeticOperand: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[MemoryReference, ArithmeticOperand]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, destination: MemoryReference, source: ArithmeticOperand) -> Move: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

@typing.final
class NopType(Instruction):
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls) -> NopType:
        r"""
        Create a new instance of this instruction type.
        
        Users should not call this method, but it is provided for `pickle` support.
        """

class Offset:
    @property
    def data_type(self) -> ScalarType: ...
    @property
    def offset(self) -> builtins.int: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[builtins.int, ScalarType]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, offset: builtins.int, data_type: ScalarType) -> Offset: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class ParseInstructionError(InstructionError):
    r"""
    Errors that may occur while parsing an ``Instruction``.
    """
    ...

class ParseMemoryReferenceError(_quil.QuilError):
    r"""
    Errors that may occur while parsing a ``MemoryReference``.
    """
    ...

class PauliSum:
    @property
    def arguments(self) -> builtins.list[builtins.str]: ...
    @property
    def terms(self) -> builtins.list[PauliTerm]: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[builtins.list[builtins.str], builtins.list[PauliTerm]]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, arguments: typing.Sequence[builtins.str], terms: typing.Sequence[PauliTerm]) -> PauliSum: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """

class PauliTerm:
    @property
    def arguments(self) -> builtins.list[tuple[PauliGate, builtins.str]]: ...
    @property
    def expression(self) -> expression.Expression: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> builtins.tuple[
            builtins.list[builtins.tuple[PauliGate, builtins.str]],
            _quil.expression.Expression
        ]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, arguments: typing.Sequence[tuple[PauliGate, builtins.str]], expression: _quil.expression.Expression) -> PauliTerm: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """

class Pragma(Instruction):
    @property
    def arguments(self) -> builtins.list[PragmaArgument]: ...
    @property
    def data(self) -> typing.Optional[builtins.str]: ...
    @property
    def name(self) -> builtins.str: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[builtins.str, builtins.list[PragmaArgument], typing.Optional[builtins.str]]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, name: builtins.str, arguments: typing.Sequence[PragmaArgument], data: typing.Optional[builtins.str]) -> Pragma: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class PragmaArgument:
    def __getnewargs__(self) -> builtins.tuple[builtins.int | builtins.str]: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...
    @typing.final
    class Identifier(PragmaArgument):
        __match_args__ = ("_0",)
        @property
        def _0(self) -> builtins.str: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...
        def __len__(self) -> builtins.int: ...
        def __new__(cls, _0: builtins.str) -> PragmaArgument.Identifier: ...
    
    @typing.final
    class Integer(PragmaArgument):
        __match_args__ = ("_0",)
        @property
        def _0(self) -> builtins.int: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...
        def __len__(self) -> builtins.int: ...
        def __new__(cls, _0: builtins.int) -> PragmaArgument.Integer: ...
    

class Pulse(Instruction):
    @property
    def blocking(self) -> builtins.bool: ...
    @blocking.setter
    def blocking(self, value: builtins.bool) -> None: ...
    @property
    def frame(self) -> FrameIdentifier: ...
    @frame.setter
    def frame(self, value: FrameIdentifier) -> None: ...
    @property
    def waveform(self) -> WaveformInvocation: ...
    @waveform.setter
    def waveform(self, value: WaveformInvocation) -> None: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[builtins.bool, FrameIdentifier, WaveformInvocation]: ...
    def __new__(cls, blocking: builtins.bool, frame: FrameIdentifier, waveform: WaveformInvocation) -> Pulse: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class Qubit:
    def __getnewargs__(self) -> builtins.tuple[builtins.int | builtins.str | QubitPlaceholder]: ...
    def __new__(cls, arg: Qubit  |  QubitPlaceholder  |  builtins.int  |  builtins.str, /) -> Qubit: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...
    @typing.final
    class Fixed(Qubit):
        __match_args__ = ("_0",)
        @property
        def _0(self) -> builtins.int: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...
        def __len__(self) -> builtins.int: ...
        def __new__(cls, _0: builtins.int) -> Qubit.Fixed: ...
    
    @typing.final
    class Placeholder(Qubit):
        __match_args__ = ("_0",)
        @property
        def _0(self) -> QubitPlaceholder: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...
        def __len__(self) -> builtins.int: ...
        def __new__(cls, _0: QubitPlaceholder) -> Qubit.Placeholder: ...
    
    @typing.final
    class Variable(Qubit):
        __match_args__ = ("_0",)
        @property
        def _0(self) -> builtins.str: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...
        def __len__(self) -> builtins.int: ...
        def __new__(cls, _0: builtins.str) -> Qubit.Variable: ...
    

class QubitPlaceholder:
    r"""
    An opaque placeholder for a qubit whose index may be assigned at a later time.
    """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __ge__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> typing.NoReturn:
        r"""
        `QubitPlaceholder`s do not support `pickle` or `deepcopy`.
        Calling this method will raise an error.
        """
    def __gt__(self, other: builtins.object, /) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __le__(self, other: builtins.object, /) -> builtins.bool: ...
    def __lt__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(cls) -> QubitPlaceholder: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    @staticmethod
    def register(n: builtins.int) -> builtins.list[QubitPlaceholder]:
        r"""
        Return a 'register' of ``n`` qubit placeholders.
        """

class RawCapture(Instruction):
    @property
    def blocking(self) -> builtins.bool: ...
    @property
    def duration(self) -> expression.Expression: ...
    @property
    def frame(self) -> FrameIdentifier: ...
    @property
    def memory_reference(self) -> MemoryReference: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[builtins.bool, FrameIdentifier, expression.Expression, MemoryReference]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, blocking: builtins.bool, frame: FrameIdentifier, duration: expression.Expression, memory_reference: MemoryReference) -> RawCapture: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class Reset(Instruction):
    @property
    def qubit(self) -> typing.Optional[Qubit]: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[typing.Optional[Qubit]]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, qubit: typing.Optional[Qubit]) -> Reset: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class SetFrequency(Instruction):
    @property
    def frame(self) -> FrameIdentifier: ...
    @property
    def frequency(self) -> expression.Expression: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[FrameIdentifier, expression.Expression]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, frame: FrameIdentifier, frequency: expression.Expression) -> SetFrequency: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class SetPhase(Instruction):
    @property
    def frame(self) -> FrameIdentifier: ...
    @property
    def phase(self) -> expression.Expression: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[FrameIdentifier, expression.Expression]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, frame: FrameIdentifier, phase: expression.Expression) -> SetPhase: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class SetScale(Instruction):
    @property
    def frame(self) -> FrameIdentifier: ...
    @property
    def scale(self) -> expression.Expression: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[FrameIdentifier, expression.Expression]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, frame: FrameIdentifier, scale: expression.Expression) -> SetScale: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class Sharing:
    @property
    def name(self) -> builtins.str: ...
    @property
    def offsets(self) -> builtins.list[Offset]: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[builtins.str, builtins.list[Offset]]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, name: builtins.str, offsets: typing.Sequence[Offset]) -> Sharing: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """

class ShiftFrequency(Instruction):
    @property
    def frame(self) -> FrameIdentifier: ...
    @property
    def frequency(self) -> expression.Expression: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[FrameIdentifier, expression.Expression]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, frame: FrameIdentifier, frequency: expression.Expression) -> ShiftFrequency: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class ShiftPhase(Instruction):
    @property
    def frame(self) -> FrameIdentifier: ...
    @property
    def phase(self) -> expression.Expression: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[FrameIdentifier, expression.Expression]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, frame: FrameIdentifier, phase: expression.Expression) -> ShiftPhase: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class Store(Instruction):
    @property
    def destination(self) -> builtins.str: ...
    @property
    def offset(self) -> MemoryReference: ...
    @property
    def source(self) -> ArithmeticOperand: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[builtins.str, MemoryReference, ArithmeticOperand]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, destination: builtins.str, offset: MemoryReference, source: ArithmeticOperand) -> Store: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class SwapPhases(Instruction):
    @property
    def frame_1(self) -> FrameIdentifier: ...
    @property
    def frame_2(self) -> FrameIdentifier: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[FrameIdentifier, FrameIdentifier]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, frame_1: FrameIdentifier, frame_2: FrameIdentifier) -> SwapPhases: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class Target:
    def __getnewargs__(self) -> builtins.tuple[builtins.str | TargetPlaceholder]: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...
    @typing.final
    class Fixed(Target):
        __match_args__ = ("_0",)
        @property
        def _0(self) -> builtins.str: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...
        def __len__(self) -> builtins.int: ...
        def __new__(cls, _0: builtins.str) -> Target.Fixed: ...
    
    @typing.final
    class Placeholder(Target):
        __match_args__ = ("_0",)
        @property
        def _0(self) -> TargetPlaceholder: ...
        def __getitem__(self, key: builtins.int, /) -> typing.Any: ...
        def __len__(self) -> builtins.int: ...
        def __new__(cls, _0: TargetPlaceholder) -> Target.Placeholder: ...
    

class TargetPlaceholder:
    r"""
    An opaque placeholder for a label whose index may be assigned
    at a later time.
    """
    @property
    def base_label(self) -> builtins.str: ...
    @property
    def prefix(self) -> builtins.str:
        r"""
        Get the `Placeholder`'s `base_label`.
        
        This is deprecated; use `base_label` instead.
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __ge__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[builtins.str]: ...
    def __gt__(self, other: builtins.object, /) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __le__(self, other: builtins.object, /) -> builtins.bool: ...
    def __lt__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(cls, base_label: builtins.str = 'L', *, prefix: typing.Optional[builtins.str] = None, placeholder: typing.Optional[TargetPlaceholder] = None) -> TargetPlaceholder:
        r"""
        Create a new `TargetPlaceholder`.
        
        If you are only constructing a `TargetPlaceholder` to pass to the `Label` constructor,
        note that you can use ``Label()`` or ``Label("L", placeholder=True)``
        and access the ``target`` attribute instead.
        
        The keyword-only `prefix` and `placeholder` parameters are deprecated,
        but made available to ease the transition from PyQuil v4's `LabelPlaceholder`.
        New code should use ``Label("L", placeholder=True)`` instead.
        """
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """

class UnaryLogic(Instruction):
    @property
    def operand(self) -> MemoryReference: ...
    @property
    def operator(self) -> UnaryOperator: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[UnaryOperator, MemoryReference]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, operator: UnaryOperator, operand: MemoryReference) -> UnaryLogic: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class Vector:
    @property
    def data_type(self) -> ScalarType: ...
    @property
    def length(self) -> builtins.int: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[ScalarType, builtins.int]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, data_type: ScalarType, length: builtins.int) -> Vector: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

@typing.final
class WaitType(Instruction):
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls) -> WaitType:
        r"""
        Create a new instance of this instruction type.
        
        Users should not call this method, but it is provided for `pickle` support.
        """

class Waveform:
    @property
    def matrix(self) -> builtins.list[expression.Expression]: ...
    @property
    def parameters(self) -> builtins.list[builtins.str]: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, matrix: typing.Sequence[expression.Expression], parameters: typing.Sequence[builtins.str]) -> Waveform: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """

class WaveformDefinition(Instruction):
    @property
    def definition(self) -> Waveform: ...
    @property
    def name(self) -> builtins.str: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[builtins.str, Waveform]: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, name: builtins.str, definition: Waveform) -> WaveformDefinition: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

class WaveformInvocation:
    @property
    def name(self) -> builtins.str: ...
    @property
    def parameters(self) -> builtins.dict[builtins.str, expression.Expression]: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __getnewargs__(self) -> tuple[builtins.str, builtins.dict[builtins.str, expression.Expression]]: ...
    def __new__(cls, name: builtins.str, parameters: typing.Optional[typing.Mapping[builtins.str, expression.Expression  |  MemoryReference  |  builtins.int  |  builtins.float  |  builtins.complex]] = None) -> WaveformInvocation: ...
    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def __str__(self) -> builtins.str:
        r"""
        Get a Quil-like representation as a string.
        """
    def out(self) -> builtins.str:
        r"""
        Get a Quil representation as a string.
        
        This method is deprecated; you should use `to_quil` instead.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

@typing.final
class ArithmeticOperator(enum.Enum):
    ADD = ...
    SUBTRACT = ...
    DIVIDE = ...
    MULTIPLY = ...

    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

@typing.final
class BinaryOperator(enum.Enum):
    r"""
    Bitwise operators.  These are "binary" in the sense that they operate on *binary
    representations*, not in the sense that they take two arguments (although they also do that).
    """
    AND = ...
    r"""
    Bitwise and.  The same as Rust's and Python's `&`.
    """
    IOR = ...
    r"""
    Bitwise (inclusive) or.  The same as Rust's and Python's `|`.
    """
    XOR = ...
    r"""
    Bitwise exclusive or.  The same as Rust's and Python's `^`.
    """
    SHL = ...
    r"""
    Bitwise left shift.  The same as Rust's and Python's `<<`.
    
    As per the Quil specification, shifting by a negative number of bits is forbidden, and
    shifting by as many or more bits than are present in a word fills the entire word with `0`s.
    """
    SHR = ...
    r"""
    Bitwise logical right shift.  The same as Rust's unsigned-type `>>`.  Python does not
    provide this operation, as its integers are natively infinite-width.
    
    As per the Quil specification, shifting by a negative number of bits is forbidden, and
    shifting by as many or more bits than are present in a word fills the entire word with `0`s.
    """
    ASHR = ...
    r"""
    Bitwise logical right shift.  The same as Rust's signed-type `>>` and the same as Python's
    `>>` (as Python natively has infinite-width signed integers).  `ASHR n k` is equivalent to
    `⌊n / 2ᵏ⌋` assuming a 2's complement representation of integers.
    
    As per the Quil specification, shifting by a negative number of bits is forbidden, and
    shifting by as many or more bits than are present in a word fills the entire word with the
    existing top bit of the word.
    """

    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

@typing.final
class ComparisonOperator(enum.Enum):
    EQUAL = ...
    GREATER_THAN_OR_EQUAL = ...
    GREATER_THAN = ...
    LESS_THAN_OR_EQUAL = ...
    LESS_THAN = ...

    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

@typing.final
class GateModifier(enum.Enum):
    r"""
    An enum of all the possible modifiers on a quil [`Gate`]
    """
    CONTROLLED = ...
    r"""
    The `CONTROLLED` modifier makes the gate take an extra [`Qubit`] parameter as a control
    qubit.
    """
    DAGGER = ...
    r"""
    The `DAGGER` modifier does a complex-conjugate transpose on the [`Gate`].
    """
    FORKED = ...
    r"""
    The `FORKED` modifier allows an alternate set of parameters to be used based on the state
    of a qubit.
    """

    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    @staticmethod
    def from_str(modifier: builtins.str) -> GateModifier: ...
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

@typing.final
class GateType(enum.Enum):
    r"""
    The type of a [`GateDefinition`].
    """
    MATRIX = ...
    PERMUTATION = ...
    PAULI_SUM = ...
    SEQUENCE = ...

    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

@typing.final
class PauliGate(enum.Enum):
    I = ...
    X = ...
    Y = ...
    Z = ...

    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    @staticmethod
    def parse(input: builtins.str) -> PauliGate:
        r"""
        Parse a ``PauliGate`` from a string.
        
        Raises a ``ParseExpressionError`` error if the string isn't a valid Quil expression.
        """

@typing.final
class ScalarType(enum.Enum):
    BIT = ...
    INTEGER = ...
    OCTET = ...
    REAL = ...

    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

@typing.final
class UnaryOperator(enum.Enum):
    NEG = ...
    NOT = ...

    def __repr__(self) -> builtins.str:
        r"""
        Implements `__repr__` for Python in terms of the Rust
        [`Debug`](std::fmt::Debug) implementation.
        """
    def to_quil(self) -> builtins.str: ...
    def to_quil_or_debug(self) -> builtins.str: ...

def unpack_classical_reg(obj: typing.Any) -> MemoryReference:
    r"""
    Get the address for a classical register.
    
    This can be used to convert a `(str, int)` or `[str, int]` into a `MemoryReference`,
    or to convert a `DeclarationAt` or `Declaration` into a `MemoryReference`.
    """

