# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405
r"""
The `quil` package provides tools for constructing, manipulating,
parsing, and printing [Quil](https://github.com/quil-lang/quil) programs.

⚠️ This package is still in early development
and breaking changes should be expected between minor versions.
"""

import builtins
from . import expression
from . import instructions
from . import program
from . import validation
from . import waveform
__all__ = [
    "PickleError",
    "QuilError",
    "ToQuilStringError",
    "ValueError",
    "expression",
    "instructions",
    "program",
    "validation",
    "waveform",
]

class PickleError(QuilError):
    r"""
    Errors when trying to pickle or deepcopy.
    """
    ...

class QuilError(builtins.Exception):
    r"""
    Base exception type for errors raised by this package.
    """
    ...

class ToQuilStringError(QuilError):
    r"""
    Errors which can occur when converting a Quil item to a string.
    """
    ...

class ValueError(QuilError):
    r"""
    Raised when an argument to a quil function has an inappropriate value.
    """
    ...

