[env]
RUST_BACKTRACE = 0

[tasks.poetry-install]
command = "poetry"
args = ["install"]

[tasks.install-quil]
command = "poetry"
args = ["run", "maturin", "develop"]

[tasks.stubtest]
command = "poetry"
args = ["run", "stubtest", "quil"]

[tasks.stubtest-flow]
dependencies = [
    "poetry-install",
    "install-quil",
    "stubtest",
]
