[env]
RUST_BACKTRACE = 0

[tasks.poetry-install]
command = "poetry"
args = ["install"]

[tasks.install-quil]
command = "poetry"
args = ["run", "maturin", "develop"]

[tasks.stubtest]
command = "poetry"
args = ["run", "stubtest", "--allowlist", ".stubtest-allowlist", "quil"]

[tasks.stubtest-flow]
dependencies = [
    "poetry-install",
    "install-quil",
    "stubtest",
]

[tasks.pytest]
command = "poetry"
args = ["run", "pytest"]

[tasks.pytest-flow]
dependencies = [
    "poetry-install",
    "install-quil",
    "pytest",
]

[tasks.py-docs]
dependencies = [
    "poetry-install",
    "install-quil"
]
command = "poetry"
args = ["run", "python", "make_docs.py"]

[tasks.dev-flow]
dependencies = ["dev-test-flow", "pytest-flow", "stubtest"]

[tasks.default]
alias = "dev-flow"
