[package]
name = "program-stats"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.6.4"
quil-rs = { path = "../quil-rs" }
thiserror = "1.0.56"

[dev-dependencies]
rstest = "0.18.2"
