[package]
name = "optipy"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = { version = "2.0.104", features = [ "full", "visit-mut" ] }

