# Based on https://github.com/actions-rs/meta/blob/master/recipes/msrv.md

on: [ push, pull_request ]

name: Benchmark

jobs:
  benchmark:
    name: Run benchmarks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
        
      - uses: Swatinem/rust-cache@v1
    
      - name: Download benchmark artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: bench.yml
          name: benchmarks
          path: target/criterion
        continue-on-error: true
      
      - name: Run cargo benchmark
        uses: actions-rs/cargo@v1
        with: 
          command: bench
          args: --bench parser -- --warm-up-time=2 --measurement-time=2 --sample-size=500 --color=always
      
      - name: Archive benchmark results
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@v3
        with:
          name: benchmarks
          path: target/criterion
    