# Based on https://github.com/actions-rs/meta/blob/master/recipes/msrv.md

on: [ pull_request ]

name: Benchmark

jobs:
  benchmark:
    name: Run benchmarks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set env vars
        run: |
          THIS_SHA=$(echo $GITHUB_SHA | cut -c 1-7)
          MAIN_SHA=$(echo $(git rev-parse main) | cut -c 1-7)

          echo "THIS_BENCH=${THIS_SHA}.bench" >> $GITHUB_ENV
          echo "MAIN_BENCH=${MAIN_SHA}.bench" >> $GITHUB_ENV

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
        
      - uses: Swatinem/rust-cache@v1
        
      - name: Install critcmp
        run: cargo install critcmp

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      # - name: Download benchmark artifacts
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: benchmarks
      
      - name: Run cargo benchmark
        uses: actions-rs/cargo@v1
        with: 
          command: bench
          args: --bench parser -- --save-baseline $THIS_SHA
      
      - name: Archive benchmark results
        uses: actions/upload-artifact@v3
        with:
          name: benchmarks
          path: target/criterion
      
      # - name: Compare benchmark to main
      #   run: |
      #     echo "comparing this benchmark to $MAIN_BENCH (main)"
      #     critcmp $MAIN_BENCH $THIS_BENCH