name: Prepare Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      type:
        description: Bump versions and trigger a new release.
        required: true
        default: release
        options:
          - release
          - prerelease

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
      # Knope uses KNOPE_PRELEASE_LABEL, so use this instead to avoid unintended behavior
      PRERELEASE_LABEL: rc
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT }}
    - name: Install Knope
      uses: knope-dev/action@v1
      with:
        version: 0.7.0 # Test before updating, breaking changes likely: https://github.com/knope-dev/action#install-latest-version
    - run: |
        git config --global user.name "${{ github.triggering_actor }}"
        git config --global user.email "${{ github.triggering_actor}}@users.noreply.github.com"
    - name: Prepare Prerelease
      run: knope release --prerelease-label "${PRERELEASE_LABEL}"
      if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.type == 'prerelease')
    - name: Prepare Release
      run: knope release
      if: github.event_name == 'workflow_dispatch' && inputs.type == 'release'
