name: Prepare Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      type:
        description: Bump versions and trigger a new release.
        required: true
        default: release
        options:
          - release
          - prerelease

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT }}
    - name: Install Knope
      uses: knope-dev/action@v1
      with:
        version: 0.6.1 # Test before updating, breaking changes likely: https://github.com/knope-dev/action#install-latest-version
    - run: |
        git config --global user.name "${{ github.triggering_actor }}"
        git config --global user.email "${{ github.triggering_actor}}@users.noreply.github.com"
    - name: Prepare Prerelease
      run: knope prerelease
      if: github.event_name == 'push'
    - name: Prepare Release
      run: knope ${{ inputs.type }}
      if: github.event_name == 'workflow_dispatch'
