name: Publish quil-py documentation

on:
  release:
    types: [published]
  workflow_dispatch:
    description: "Manually build and publish quil-py documentation to GitHub pages."
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install poetry
        uses: snok/install-poetry@v1
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make
      - name: Build quil-py documentation
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: --cwd quil-py --makefile Makefile.toml docs
      - uses: actions/upload-artifact@v3
        with:
          name: docs-artifact
          path: quil-py/build/docs
      - name: Upload pages artifact
      - uses: actions/upload-pages-artifact@v2
        with:
          path: quil-py/build/docs
        
  publish-preview:
    runs-on: ubuntu-latest
    needs: build-docs
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: docs-artifact
          path: docs
      - name: Deploy preview
      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: docs
          preview-branch: main
          umbrella-dir: docs/pr-preview

  deploy-docs:
    needs: publish-docs
    if: ${{ github.event_name == 'workflow_dispatch' || startsWith(github.event.release.tag_name, 'quil-py/v') }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
