on:
  pull_request:

name: Release dry-run

jobs:
  dry-run:
    name: Dry-run cargo publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - run: cargo publish --manifest-path=quil-rs/Cargo.toml --dry-run
      - run: cargo publish --manifest-path=quil-py/Cargo.toml --dry-run
